export type Term = [number, number, number]; // [A, B, C]
export type Series = Term[];
export type PlanetSeries = {
    L: Series[];  // L0, L1, L2, ...
    B: Series[];  // B0, B1, ...
    R: Series[];  // R0, R1, ...
};
export type VSOP87Data = Record<string, PlanetSeries>;