import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const PLANETS: Record<string, string> = {
    mercury: "VSOP87B.mer",
    venus: "VSOP87B.ven",
    earth: "VSOP87B.ear",
    mars: "VSOP87B.mar",
    jupiter: "VSOP87B.jup",
    saturn: "VSOP87B.sat",
    uranus: "VSOP87B.ura",
    neptune: "VSOP87B.nep",
};

const VARIABLE_MAP: Record<number, string> = { 1: "L", 2: "B", 3: "R" };
const AMPLITUDE_THRESHOLD = 0;
const DATA_DIR = join(__dirname, "../scripts/vsop87");

interface Term {
    A: number;
    B: number;
    C: number;
}

interface SeriesMap {
    L: Map<number, Term[]>;
    B: Map<number, Term[]>;
    R: Map<number, Term[]>;
}

function parsePlanet(filename: string): SeriesMap {
    const lines = readFileSync(join(DATA_DIR, filename), "utf-8").split("\n");
    const result: SeriesMap = { L: new Map(), B: new Map(), R: new Map() };

    let currentVar: "L" | "B" | "R" | null = null;
    let currentPower = 0;

    for (const line of lines) {
        // Header line
        if (line.includes("VARIABLE")) {
            const varMatch = line.match(/VARIABLE\s+(\d)/);
            const powerMatch = line.match(/\*T\*\*(\d)/);
            if (!varMatch || !powerMatch) continue;
            const varNum = parseInt(varMatch[1]);
            currentVar = VARIABLE_MAP[varNum] as "L" | "B" | "R" ?? null;
            currentPower = parseInt(powerMatch[1]);
            if (currentVar && !result[currentVar].has(currentPower)) {
                result[currentVar].set(currentPower, []);
            }
            continue;
        }

        if (!currentVar) continue;

        // Data line - extract the last three floats
        const floats = line.trim().split(/\s+/).map(Number).filter(n => !isNaN(n));
        if (floats.length < 5) continue;

        const A = floats[floats.length - 3];
        const B = floats[floats.length - 2];
        const C = floats[floats.length - 1];

        if (A < AMPLITUDE_THRESHOLD) continue;

        result[currentVar].get(currentPower)!.push({ A, B, C });
    }

    return result;
}

function seriesMapToCode(map: Map<number, Term[]>): string {
    const powers = Array.from(map.keys()).sort((a, b) => a - b);
    return "[\n" + powers.map(k => {
        const terms = map.get(k)!;
        const rows = terms.map(({ A, B, C }) =>
            `            [${A.toFixed(11)}, ${B.toFixed(11)}, ${C.toFixed(11)}],`
        ).join("\n");
        return `        // series ${k}\n        [\n${rows}\n        ],`;
    }).join("\n") + "\n    ]";
}

function generateFile(): string {
    const planetEntries = Object.entries(PLANETS).map(([name, file]) => {
        const series = parsePlanet(file);
        return `    ${name}: {
        L: ${seriesMapToCode(series.L)},
        B: ${seriesMapToCode(series.B)},
        R: ${seriesMapToCode(series.R)},
    }`;
    }).join(",\n");

    return `// AUTO-GENERATED by scripts/parseVsop87.ts - DO NOT EDIT
// Source: VSOP87 (Bretagnon & Francou, 1988) via CDS VI/81
// Amplitude threshold: ${AMPLITUDE_THRESHOLD}
import type { VSOP87Data } from "./vsop87Types";

export const VSOP87_DATA: VSOP87Data = {
${planetEntries}
};
`;
}

writeFileSync(
    join(__dirname, "../src/core/orbit/vsop87Data.ts"),
    generateFile(),
    "utf-8"
);

console.log("vsop87Data.ts generated successfully.");